//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expendiente.conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cita()
        {
            this.detalle_cita = new HashSet<detalle_cita>();
            this.usuario_cita = new HashSet<usuario_cita>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_estado_cita { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string motivo { get; set; }
        public string is_Deleted { get; set; }
    
        public virtual estados_citas estados_citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_cita> detalle_cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_cita> usuario_cita { get; set; }
    }
}
