//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expendiente.conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactos_emergencia
    {
        public int id { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string parentesco { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
