//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expendiente.conn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<citas> citas { get; set; }
        public virtual DbSet<contactos_emergencia> contactos_emergencia { get; set; }
        public virtual DbSet<detalle_cita> detalle_cita { get; set; }
        public virtual DbSet<Estados_citas> Estados_citas { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<usuario_cita> usuario_cita { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
